### ISSUE TITLE
Question about moving command

### ISSUE THREAD

**Issue by u10116032** [Cubillosxy/MYO-PYTHON-BEBOP#1]
Dear Author:

Hi, I'm developing an app to control my bebop2 in c# for windows.

I only found the protocol about takeoff and landing, and other network protocol from the official pdf.

I'm writing the function of pilotting and the videostream, could you give me some suggestion?

I know there are lots of command type(e.g. non ack/ack/low latency/..), but here's my question: what's the command data type?

for example: for takeoff, the data type is 1010 per byte, for landing, the data type is 1030, but how is other command?

do you have something like Instruction Manual?

Thanks for your support!!

Best Regards,
Halley

**Comment by Cubillosxy** [comment]
Hi

this project is perfect for you
https://github.com/Ruslan-B/AR.Drone  
there is a library in C#/.Net for controller the AR.DRONE 2.0    

Best Regards,
Edwin
